### ISSUE TITLE
Map image uses http url

### ISSUE THREAD

**Issue by HSZemi** [SiegeEngineers/aocrecs.com#5]
The map preview image is loaded from http instead of https. This leads to a "not secure" indicator in the web browser due to mixed content.

The http url is already present in the api response and seems to stem from [here](https://github.com/SiegeEngineers/aocrecs.com/blob/master/python/aocrecs/logic/matches.py#L202).

I would have provided a pull request, but I could not find out where to fix it :frowning_man:

**Comment by happyleavesaoc** [comment]
Fixed in https://github.com/SiegeEngineers/aocrecs.com/commit/209e1de099da64b13d5e4c7499d14a3f1606f8f0
