### ISSUE TITLE
API gateway seems to be down

### ISSUE THREAD

**Issue by karx** [SiegeEngineers/aocrecs.com#8]
The API server seems to be down atm. 
* Getting `502 Bad Gateway` if I try access: https://aocrecs.com/api
* The aocrecs website also shows `Network error: JSON.parse: .....` on landing page. 

Is this a build issue or something else. Let me know if I can help.

**Comment by happyleavesaoc** [comment]
Restarted - working now. Crash to be investigated. Thanks for the note!
